package inheritance;

public class Notes {
	
	/* KALITIMIN IKI AMACI VARDIR 
	 * 
	 * KOD TEKRARINI ONLEMEK(RESUABLE KOD YAPISINI SAGLAMAK)
	 * POLÝFORMÝZM'I SAGLAMAKTIR(YANI OVERRIDE KAVRAMI)
	 * JAVADA EXTENDS KELÝMEÝ ÝLE YAPILIR
	 * JAVADA MULTIPLE INHERITANCE YOKTUR
	 * BOYLELIKLE DIAMOND PROBLEM ENGELLENIS OLUR.
	 * 
	 * 
	 * SUBCLASS SUPERCLASS'TAN DAGHA OZEL OLMALIDIR.YOKSA INHERITANCE'IN BIR ANLAMI YOKTUR.
	 */
	
	
	

}
